name: Check Version

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-version:
    if: ${{ github.event_name == 'pull_request' }}
    name: Check Version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [ 'docbuilder' ]
    steps:
      - name: Run the check-version action
        id: run-check-version
        uses: GenapsysInc/internal-actions/reusable-actions/check-version@main
        with:
          json: ${{ matrix.directory }}/meta.json
          include-paths: '${{ matrix.directory }}/**/*.py ${{ matrix.directory }}/Dockerfile'
          token: ${{ secrets.GH_ACTION }}
